"""Stable decision_support reason-code constants."""

from __future__ import annotations

EVIDENCE_AVAILABLE = "EVIDENCE_AVAILABLE"
EVIDENCE_MISSING = "EVIDENCE_MISSING"
EVIDENCE_STALE = "EVIDENCE_STALE"
EVIDENCE_WEAK = "EVIDENCE_WEAK"
EVIDENCE_SUFFICIENT = "EVIDENCE_SUFFICIENT"
EVIDENCE_CONTRADICTORY = "EVIDENCE_CONTRADICTORY"
INSUFFICIENT_EVIDENCE = "INSUFFICIENT_EVIDENCE"
CRITIC_BLOCKED = "CRITIC_BLOCKED"

REDEMPTION_FEE_RISK = "REDEMPTION_FEE_RISK"
FEE_LOCKUP = "FEE_LOCKUP"
THEME_OVERWEIGHT = "THEME_OVERWEIGHT"
RIGHT_SIDE_UNCONFIRMED = "RIGHT_SIDE_UNCONFIRMED"
MOMENTUM_UNCONFIRMED = "MOMENTUM_UNCONFIRMED"
NEWS_NEGATIVE = "NEWS_NEGATIVE"
NEWS_POSITIVE_BUT_PRICE_WEAK = "NEWS_POSITIVE_BUT_PRICE_WEAK"
BENCHMARK_DIVERGENCE = "BENCHMARK_DIVERGENCE"
PROFIT_PROTECTION = "PROFIT_PROTECTION"
LOSS_CONTROL = "LOSS_CONTROL"
EVENT_HYPE_FAILED = "EVENT_HYPE_FAILED"
CASH_BUFFER_LOW = "CASH_BUFFER_LOW"
CASH_DEPLOYMENT_NOT_READY = "CASH_DEPLOYMENT_NOT_READY"
SHORT_TERM_BUDGET_EXCEEDED = "SHORT_TERM_BUDGET_EXCEEDED"
TRANSACTION_HISTORY_MISSING = "TRANSACTION_HISTORY_MISSING"
USER_CONSTRAINT_MISSING = "USER_CONSTRAINT_MISSING"
VALUATION_UNKNOWN = "VALUATION_UNKNOWN"

BUDGET_BLOCKED = "BUDGET_BLOCKED"
CONSTRAINT_BLOCKED = "CONSTRAINT_BLOCKED"
RISK_PROFILE_MISSING = "RISK_PROFILE_MISSING"
LIQUIDITY_NEED_UNKNOWN = "LIQUIDITY_NEED_UNKNOWN"

DOWNGRADED_ACTIVE_TO_HOLD = "DOWNGRADED_ACTIVE_TO_HOLD"
PASSIVE_ACTION = "PASSIVE_ACTION"
ACTIVE_ACTION_ALLOWED = "ACTIVE_ACTION_ALLOWED"

ALL_REASON_CODES: tuple[str, ...] = (
    EVIDENCE_AVAILABLE,
    EVIDENCE_MISSING,
    EVIDENCE_STALE,
    EVIDENCE_WEAK,
    EVIDENCE_SUFFICIENT,
    EVIDENCE_CONTRADICTORY,
    INSUFFICIENT_EVIDENCE,
    CRITIC_BLOCKED,
    REDEMPTION_FEE_RISK,
    FEE_LOCKUP,
    THEME_OVERWEIGHT,
    RIGHT_SIDE_UNCONFIRMED,
    MOMENTUM_UNCONFIRMED,
    NEWS_NEGATIVE,
    NEWS_POSITIVE_BUT_PRICE_WEAK,
    BENCHMARK_DIVERGENCE,
    PROFIT_PROTECTION,
    LOSS_CONTROL,
    EVENT_HYPE_FAILED,
    CASH_BUFFER_LOW,
    CASH_DEPLOYMENT_NOT_READY,
    SHORT_TERM_BUDGET_EXCEEDED,
    TRANSACTION_HISTORY_MISSING,
    USER_CONSTRAINT_MISSING,
    VALUATION_UNKNOWN,
    BUDGET_BLOCKED,
    CONSTRAINT_BLOCKED,
    RISK_PROFILE_MISSING,
    LIQUIDITY_NEED_UNKNOWN,
    DOWNGRADED_ACTIVE_TO_HOLD,
    PASSIVE_ACTION,
    ACTIVE_ACTION_ALLOWED,
)
