"""Stable decision_support reason-code constants.

evidence_state semantics (no schema migration — documentation only):
- ANCHORED: Sufficient anchored evidence supports the decision direction.
- INSUFFICIENT_EVIDENCE: Evidence is missing, weak, or stale; cannot support
  an active action.
- CRITIC_BLOCKED: Critique pipeline rejected the proposed action.
- CONSTRAINT_BLOCKED: Evidence may exist but action is blocked by constraints
  or artifacts (redemption fee, position contribution, etc.).
- BUDGET_BLOCKED: Action is blocked by cash/budget conditions (cash
  deployment not ready, cash buffer low, etc.).
- DOWNGRADED: Gatekeeper downgraded an active action to HOLD/WAIT due to
  one or more blockers.
"""

from __future__ import annotations

EVIDENCE_STATE_ANCHORED = "ANCHORED"
EVIDENCE_STATE_INSUFFICIENT_EVIDENCE = "INSUFFICIENT_EVIDENCE"
EVIDENCE_STATE_CRITIC_BLOCKED = "CRITIC_BLOCKED"
EVIDENCE_STATE_CONSTRAINT_BLOCKED = "CONSTRAINT_BLOCKED"
EVIDENCE_STATE_BUDGET_BLOCKED = "BUDGET_BLOCKED"
EVIDENCE_STATE_DOWNGRADED = "DOWNGRADED"

ALL_EVIDENCE_STATES: tuple[str, ...] = (
    EVIDENCE_STATE_ANCHORED,
    EVIDENCE_STATE_INSUFFICIENT_EVIDENCE,
    EVIDENCE_STATE_CRITIC_BLOCKED,
    EVIDENCE_STATE_CONSTRAINT_BLOCKED,
    EVIDENCE_STATE_BUDGET_BLOCKED,
    EVIDENCE_STATE_DOWNGRADED,
)


def is_active_evidence_state(state: str) -> bool:
    return state == EVIDENCE_STATE_ANCHORED


def is_blocked_evidence_state(state: str) -> bool:
    return state in (
        EVIDENCE_STATE_INSUFFICIENT_EVIDENCE,
        EVIDENCE_STATE_CRITIC_BLOCKED,
        EVIDENCE_STATE_CONSTRAINT_BLOCKED,
        EVIDENCE_STATE_BUDGET_BLOCKED,
        EVIDENCE_STATE_DOWNGRADED,
    )

EVIDENCE_AVAILABLE = "EVIDENCE_AVAILABLE"
EVIDENCE_MISSING = "EVIDENCE_MISSING"
EVIDENCE_STALE = "EVIDENCE_STALE"
EVIDENCE_WEAK = "EVIDENCE_WEAK"
EVIDENCE_SUFFICIENT = "EVIDENCE_SUFFICIENT"
EVIDENCE_CONTRADICTORY = "EVIDENCE_CONTRADICTORY"
INSUFFICIENT_EVIDENCE = "INSUFFICIENT_EVIDENCE"
CRITIC_BLOCKED = "CRITIC_BLOCKED"

REDEMPTION_FEE_RISK = "REDEMPTION_FEE_RISK"
FEE_LOCKUP = "FEE_LOCKUP"
THEME_OVERWEIGHT = "THEME_OVERWEIGHT"
RIGHT_SIDE_UNCONFIRMED = "RIGHT_SIDE_UNCONFIRMED"
MOMENTUM_UNCONFIRMED = "MOMENTUM_UNCONFIRMED"
NEWS_NEGATIVE = "NEWS_NEGATIVE"
NEWS_POSITIVE_BUT_PRICE_WEAK = "NEWS_POSITIVE_BUT_PRICE_WEAK"
BENCHMARK_DIVERGENCE = "BENCHMARK_DIVERGENCE"
PROFIT_PROTECTION = "PROFIT_PROTECTION"
LOSS_CONTROL = "LOSS_CONTROL"
EVENT_HYPE_FAILED = "EVENT_HYPE_FAILED"
CASH_BUFFER_LOW = "CASH_BUFFER_LOW"
CASH_DEPLOYMENT_NOT_READY = "CASH_DEPLOYMENT_NOT_READY"
SHORT_TERM_BUDGET_EXCEEDED = "SHORT_TERM_BUDGET_EXCEEDED"
TRANSACTION_HISTORY_MISSING = "TRANSACTION_HISTORY_MISSING"
USER_CONSTRAINT_MISSING = "USER_CONSTRAINT_MISSING"
VALUATION_UNKNOWN = "VALUATION_UNKNOWN"

BUDGET_BLOCKED = "BUDGET_BLOCKED"
CONSTRAINT_BLOCKED = "CONSTRAINT_BLOCKED"
RISK_PROFILE_MISSING = "RISK_PROFILE_MISSING"
LIQUIDITY_NEED_UNKNOWN = "LIQUIDITY_NEED_UNKNOWN"

DOWNGRADED_ACTIVE_TO_HOLD = "DOWNGRADED_ACTIVE_TO_HOLD"
PASSIVE_ACTION = "PASSIVE_ACTION"
ACTIVE_ACTION_ALLOWED = "ACTIVE_ACTION_ALLOWED"

ALL_REASON_CODES: tuple[str, ...] = (
    EVIDENCE_AVAILABLE,
    EVIDENCE_MISSING,
    EVIDENCE_STALE,
    EVIDENCE_WEAK,
    EVIDENCE_SUFFICIENT,
    EVIDENCE_CONTRADICTORY,
    INSUFFICIENT_EVIDENCE,
    CRITIC_BLOCKED,
    REDEMPTION_FEE_RISK,
    FEE_LOCKUP,
    THEME_OVERWEIGHT,
    RIGHT_SIDE_UNCONFIRMED,
    MOMENTUM_UNCONFIRMED,
    NEWS_NEGATIVE,
    NEWS_POSITIVE_BUT_PRICE_WEAK,
    BENCHMARK_DIVERGENCE,
    PROFIT_PROTECTION,
    LOSS_CONTROL,
    EVENT_HYPE_FAILED,
    CASH_BUFFER_LOW,
    CASH_DEPLOYMENT_NOT_READY,
    SHORT_TERM_BUDGET_EXCEEDED,
    TRANSACTION_HISTORY_MISSING,
    USER_CONSTRAINT_MISSING,
    VALUATION_UNKNOWN,
    BUDGET_BLOCKED,
    CONSTRAINT_BLOCKED,
    RISK_PROFILE_MISSING,
    LIQUIDITY_NEED_UNKNOWN,
    DOWNGRADED_ACTIVE_TO_HOLD,
    PASSIVE_ACTION,
    ACTIVE_ACTION_ALLOWED,
)
