#!/usr/bin/env python3
"""Sync canonical fund-agent skills into an OpenCode Agent Skills directory.

v0.4.6 native skill install helper. The OpenCode plugin alone (Mode A)
exposes fund-agent as ``fund_agent_skills`` / ``fund_agent_skill_doc`` /
``fund_agent_runtime_hint`` custom tools. OpenCode's **native** Agent
Skills discovery is a separate mechanism: it looks for ``SKILL.md``
files under ``.opencode/skills/<slug>/SKILL.md``,
``~/.config/opencode/skills/<slug>/SKILL.md``, or
``.agents/skills/<slug>/SKILL.md``.

This script copies the five canonical hyphenated Markdown skill
directories from ``skills/`` into ``.opencode/skills/`` (or another
target) so OpenCode's native skill discovery can see them too. It
is a plain file copy helper:

- Skips ``docs/archive/fund-analyst/`` (archived legacy persona).
- Skips any ``skills/`` directory whose name contains ``_`` (the
  underscore runtime IDs are not agent-facing skill names).
- Copies ``SKILL.md`` and ``references/`` only; never copies
  ``src/``, ``tests/``, ``docs/``, or other repo metadata.
- Writes ``.opencode/skills/.fund-agent-generated.json`` as a marker
  so ``--clean`` can remove only the skills this script wrote,
  leaving user-authored skill files alone.

The script does not edit ``opencode.json``, does not start a
subprocess, does not install the Python runtime, and does not call
any network. It is metadata + Markdown only.
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Iterable

PROJECT_ROOT = Path(__file__).resolve().parent.parent
SKILLS_DIR = PROJECT_ROOT / "skills"
DEFAULT_TARGET = PROJECT_ROOT / ".opencode" / "skills"
ARCHIVE_DIR = PROJECT_ROOT / "docs" / "archive" / "fund-analyst"
MARKER_FILENAME = ".fund-agent-generated.json"

CANONICAL_SKILLS = (
    "fund-analysis",
    "decision-support",
    "news-research",
    "sentiment-analysis",
    "thesis-generation",
)


def _is_underscore_dir(name: str) -> bool:
    return "_" in name


def _iter_canonical_sources(skills_dir: Path) -> Iterable[Path]:
    """Yield the canonical hyphenated skill source directories.

    Skips underscore runtime directories and any directory that is
    not part of the canonical set. Raises if a canonical directory
    is missing — that is a repository contract violation, not a
    transient condition we should silently ignore.
    """
    if not skills_dir.is_dir():
        raise FileNotFoundError(f"skills directory not found: {skills_dir}")
    found = {p.name: p for p in skills_dir.iterdir() if p.is_dir()}
    for slug in CANONICAL_SKILLS:
        src = found.get(slug)
        if src is None:
            raise FileNotFoundError(
                f"missing canonical skill directory: skills/{slug}"
            )
        yield src


def _list_to_copy(skills_dir: Path) -> list[Path]:
    return sorted(_iter_canonical_sources(skills_dir), key=lambda p: p.name)


def _marker_payload(target: Path, version: str) -> dict:
    return {
        "schema_version": "fund-agent.opencode-skills.v1",
        "plugin": "fund-agent",
        "version": version,
        "marker_filename": MARKER_FILENAME,
        "target": str(target),
        "skills": list(CANONICAL_SKILLS),
        "note": (
            "Generated by scripts/install_opencode_skills.py. "
            "Safe to delete; --clean removes the listed skills."
        ),
    }


def _read_marker(target: Path) -> dict | None:
    marker = target / MARKER_FILENAME
    if not marker.is_file():
        return None
    try:
        return json.loads(marker.read_text(encoding="utf-8"))
    except (json.JSONDecodeError, OSError):
        return None


def _validate_canonical_skill(src: Path, target: Path) -> list[Path]:
    """Return the list of files that would be copied from ``src`` to
    ``target/<slug>/``. The list is sorted for determinism.

    Only ``SKILL.md`` and ``references/`` are copied. Underscore
    subdirectories, hidden files, and the archived ``fund-analyst``
    persona are never copied.
    """
    slug = src.name
    if _is_underscore_dir(slug):
        raise ValueError(f"refusing to copy underscore skill dir: {src}")
    if src == ARCHIVE_DIR or ARCHIVE_DIR in src.parents:
        raise ValueError(f"refusing to copy archived fund-analyst: {src}")

    out: list[Path] = []
    skill_md = src / "SKILL.md"
    if not skill_md.is_file():
        raise FileNotFoundError(
            f"canonical skill {slug} is missing SKILL.md: {skill_md}"
        )
    out.append(skill_md)
    refs = src / "references"
    if refs.is_dir():
        for path in sorted(refs.rglob("*")):
            if not path.is_file():
                continue
            if any(part.startswith(".") and part != ".gitkeep" for part in path.relative_to(refs).parts):
                continue
            out.append(path)
    return out


def _copy_skill(src: Path, target: Path, *, dry_run: bool) -> list[Path]:
    """Copy a single canonical skill directory into ``target/<slug>``.

    Returns the list of file paths relative to the skill source
    directory (e.g. ``SKILL.md`` or ``references/foo.md``). The
    caller can format them however it likes. Raises if the skill is
    missing required files.
    """
    slug = src.name
    files = _validate_canonical_skill(src, target)
    rels = [p.relative_to(src) for p in files]
    written: list[Path] = []
    for rel in rels:
        out_path = target / slug / rel
        if dry_run:
            written.append(rel)
            continue
        out_path.parent.mkdir(parents=True, exist_ok=True)
        out_path.write_bytes((src / rel).read_bytes())
        written.append(rel)
    return written


def _write_marker(target: Path, version: str, *, dry_run: bool) -> Path:
    marker = target / MARKER_FILENAME
    if dry_run:
        return marker
    target.mkdir(parents=True, exist_ok=True)
    marker.write_text(
        json.dumps(_marker_payload(target, version), indent=2) + "\n",
        encoding="utf-8",
    )
    return marker


def _plan(skills_dir: Path, target: Path) -> list[Path]:
    return _list_to_copy(skills_dir)


def cmd_sync(args: argparse.Namespace) -> int:
    skills_dir = Path(args.skills_dir).resolve() if args.skills_dir else SKILLS_DIR
    target = Path(args.target).resolve() if args.target else DEFAULT_TARGET

    if not skills_dir.is_dir():
        print(f"error: skills dir not found: {skills_dir}", file=sys.stderr)
        return 2

    if not args.dry_run:
        target.mkdir(parents=True, exist_ok=True)

    sources = _plan(skills_dir, target)
    if not args.dry_run:
        marker = _read_marker(target)
        if marker is not None and marker.get("plugin") != "fund-agent":
            print(
                f"error: target {target} has a non-fund-agent marker; "
                f"refusing to overwrite",
                file=sys.stderr,
            )
            return 2

    version = (PROJECT_ROOT / "VERSION").read_text(encoding="utf-8").strip()

    copied: list[tuple[str, list[Path]]] = []
    for src in sources:
        rel_files = _copy_skill(src, target, dry_run=args.dry_run)
        copied.append((src.name, rel_files))

    marker_path = _write_marker(target, version, dry_run=args.dry_run)

    if args.dry_run:
        print(f"[dry-run] target: {target}")
        for slug, files in copied:
            print(f"[dry-run] would copy skills/{slug}/ -> {target}/{slug}/")
            for rel in files:
                print(f"  - {slug}/{rel}")
        print(f"[dry-run] would write marker: {marker_path}")
        return 0

    print(f"target: {target}")
    for slug, files in copied:
        print(f"copied skills/{slug}/ -> {target}/{slug}/  ({len(files)} file(s))")
    print(f"wrote marker: {marker_path}")
    return 0


def _format_copied_files(copied: list[tuple[str, list[Path]]]) -> list[str]:
    """Render a flat human-readable list of copied files relative to
    the canonical source root ``skills/``."""
    out: list[str] = []
    for slug, rels in copied:
        for rel in rels:
            out.append(f"skills/{slug}/{rel.as_posix()}")
    return out


def cmd_clean(args: argparse.Namespace) -> int:
    target = Path(args.target).resolve() if args.target else DEFAULT_TARGET
    if not target.is_dir():
        print(f"nothing to clean: {target} does not exist", file=sys.stderr)
        return 0
    marker = _read_marker(target)
    if marker is None:
        print(
            f"error: no marker at {target / MARKER_FILENAME}; "
            f"refusing to --clean",
            file=sys.stderr,
        )
        return 2
    if marker.get("plugin") != "fund-agent":
        print(
            f"error: marker at {target} is not a fund-agent marker; "
            f"refusing to --clean",
            file=sys.stderr,
        )
        return 2
    skills_to_remove = list(marker.get("skills", []))
    if args.dry_run:
        print(f"[dry-run] would clean target: {target}")
        for slug in skills_to_remove:
            print(f"[dry-run] would remove {target / slug}")
        print(f"[dry-run] would remove {target / MARKER_FILENAME}")
        return 0
    for slug in skills_to_remove:
        skill_dir = target / slug
        if skill_dir.is_dir():
            import shutil
            shutil.rmtree(skill_dir)
            print(f"removed {skill_dir}")
    marker_file = target / MARKER_FILENAME
    if marker_file.is_file():
        marker_file.unlink()
        print(f"removed {marker_file}")
    return 0


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="install_opencode_skills.py",
        description=(
            "Sync canonical fund-agent skills into an OpenCode Agent "
            "Skills directory. Mode B of the v0.4.6 native skill "
            "install."
        ),
    )
    parser.add_argument(
        "--skills-dir",
        default=None,
        help="Source skills directory (default: ./skills)",
    )
    parser.add_argument(
        "--target",
        default=None,
        help=(
            "Destination root (default: ./.opencode/skills). "
            "OpenCode's native Agent Skills discovery looks under "
            "this directory."
        ),
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Print what would be done without writing anything.",
    )
    parser.add_argument(
        "--clean",
        action="store_true",
        help=(
            "Remove only the skills this script wrote (identified by "
            "the .fund-agent-generated.json marker), then delete the "
            "marker. Refuses to run if the marker is missing or not a "
            "fund-agent marker."
        ),
    )
    return parser


def main(argv: list[str] | None = None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)
    if args.clean:
        return cmd_clean(args)
    return cmd_sync(args)


if __name__ == "__main__":
    raise SystemExit(main())
